#include "SNData.h"
#include "Agency.h"
#include "Util.h"
#include <iostream>
#include <vector>

using namespace std;

// std::vector<struct SocialNetworkData> SNData::sns;

int main()
{


    // añadimos datos de redes sociales 
    SNData::newSocialNetwork("TokTik",0.8,0.1);
    SNData::newSocialNetwork("Infagram",0.6,0.05);
    SNData::newSocialNetwork("YZ",0.5,0.2);
    SNData::newSocialNetwork("JungleBook",0.1,0.1);


    // constructor
    Agency ag("Amasando pasta SL",200);
    
    cout << ag.getName() << endl;// "Amasando pasta SL");
    cout << ag.getMoney() << endl;// 200,0.01);

    ag.addInfluencer("Curro",0.3);
    
    Influencer *pi;
    // no está lo encuentra, debe lanzar la excepción    
    
    try {
      pi=ag.searchInfluencer("Brian"); // EXCEPTION_INFL_NOT_FOUND
    } catch (Exception e) {
       if (e == EXCEPTION_INFL_NOT_FOUND) {
          cout << "OK" <<endl;
       
       }
    
    }
    
    // esto no debe lanzar la excepción (si se ha añadido bien)
    pi=ag.searchInfluencer("Curro");
    cout << pi->getName() << endl; // "Curro"
    cout << pi->getCommission() << endl; // 0.3,0.01);
    
    ag.addInfluencer("Naranjito",0.4);
    
    // operator<<

    cout << "Agency:AmasandopastaSL[200]Influencer:Curro(0.3)Influencer:Naranjito(0.4)"<< endl 
       << ag <<endl;  // "Agency:AmasandopastaSL[200]Influencer:Curro(0.3)Influencer:Naranjito(0.4)"));

    ag.addFollowers("Curro","TokTik",1000);

    cout  <<  "Agency:AmasandopastaSL[200]Influencer:Curro(0.3)[TokTik|1000|0]Influencer:Naranjito(0.4)" << endl
       << ag << endl;  // "Agency:AmasandopastaSL[200]Influencer:Curro(0.3)[TokTik|1000|0]Influencer:Naranjito(0.4)"));

    ag.deleteInfluencer("Naranjito");
    cout << "Agency:AmasandopastaSL[200]Influencer:Curro(0.3)[TokTik|1000|0]" << endl << 
       ag << endl; // ("Agency:AmasandopastaSL[200]Influencer:Curro(0.3)[TokTik|1000|0]"));

    // newEvent
    string snNames[] = { "TokTik", "JungleBook", "Infagram", "MSN", "YZ" };
    double evRat[]   = {  0.95,   0.05, 0.7, 0.003, 0.85 };
    vector<string> inm;
    inm.push_back("Naranjito");    // no está, lo hemos borrado
    inm.push_back("Pijus Ticus");  // no está
    inm.push_back("Curro");
    inm.push_back("Pijus Magnificus");  // tampoco está
    
    ag.newEvent(inm,5,snNames,evRat);
    
    cout << "Agency:AmasandopastaSL[200]Influencer:Curro(0.3)[TokTik|2187|118.7]" << endl<<
       ag << endl;  // ("Agency:AmasandopastaSL[200]Influencer:Curro(0.3)[TokTik|2187|118.7]"));

    cout << ag.collectCommissions()<< endl;// ,35.61,0.01);    
    cout  << "Agency:AmasandopastaSL[235.61]Influencer:Curro(0.3)[TokTik|2187|0]" << endl << 
       ag << endl;   // ("Agency:AmasandopastaSL[235.61]Influencer:Curro(0.3)[TokTik|2187|0]"));



   // SNData::newSocialNetwork("TokTik",0.8,0.1);
   // SNData::newSocialNetwork("Infagram",0.6,0.05);
   // SNData::newSocialNetwork("YZ",0.5,0.2);
   // SNData::newSocialNetwork("JungleBook",0.1,0.1);

   // Agency pufosAmos("Los pufos amos",1000.0);
   // 
   // pufosAmos.addInfluencer("Pijus Magnificus",0.25);
   // // cout<<"1"<<endl;
   // pufosAmos.addInfluencer("Brian",0.15);
   // // cout<<"2"<<endl;

   // pufosAmos.addInfluencer("Brian",0.55);   // ERR_DUPLICATED
   // // cout<<"3"<<endl;
   // pufosAmos.addInfluencer("Loretta",1.05); // ERR_WRONG_COMMISSION 
   // // cout<<"4"<<endl;

   // pufosAmos.addInfluencer("Loretta",.75);
   // // cout<<"5"<<endl;

   // cout << pufosAmos ;   
   // // cout<<"6"<<endl;

   // pufosAmos.addFollowers("Pijus Magnificus", "YZ", 500);
   // // cout<<"7"<<endl;
   // pufosAmos.addFollowers("Bdian","MSNotExist",400);    // ERR_NOT_FOUND
   // // cout<<"8"<<endl;
   // pufosAmos.addFollowers("Brian","MSNotExist",400);    // ERR_UNKNOWN_SN
   // // cout<<"9"<<endl;
   // pufosAmos.addFollowers("Loretta","TokTik",1200);
   // // cout<<"10"<<endl;
   // pufosAmos.addFollowers("Loretta","Infagram",1300);
   // // cout<<"11"<<endl;
   // pufosAmos.addFollowers("Loretta","YZ",700);
   // // cout<<"12"<<endl;
   // pufosAmos.addFollowers("Loretta","TokTik",300);
   // // cout<<"13"<<endl;
   // pufosAmos.addFollowers("Brian","JungleBook",65);
   // // cout<<"14"<<endl;

   // cout << pufosAmos ;   
   // // cout<<"15"<<endl;
   // 

   // // Event data
   // cout << "---------- First event -----------" << endl;
   // string snNames[] = { "TokTik", "JungleBook", "Infagram", "MSN", "YZ" };
   // double evRat[]   = {  0.95,   0.05, 0.7, 0.003, 0.85 };
   // vector<string> inm;
   // inm.push_back("Loretta");
   // inm.push_back("Pijus Ticus");  // ignore
   // inm.push_back("Brian");
   // inm.push_back("Pijus Magnificus");

   // pufosAmos.newEvent(inm,5,snNames,evRat);
   // // cout<<"16"<<endl;
   // cout << pufosAmos ;   
   // // cout<<"17"<<endl;


   // double moneyEvent = pufosAmos.collectCommissions();
   // // cout<<"18"<<endl;
   // cout << "Money generated by the event: " << moneyEvent << endl
   //      << pufosAmos ;
   // // cout<<"19"<<endl;

   return 0;
}
